name: Build and deploy java in webapp

on:
 workflow_dispatch: 

permissions:
  id-token: write
  contents: read
  

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6.0.0

      - name: Set up Java
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '11' # Change if your app uses a different version
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -pl petstore-ee7 -am -Dmaven.compiler.release=11

      
      - name: Upload build artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: java-app
          path: petstore-ee7/target/*.war
         
  Deploy:
     runs-on: ubuntu-latest
     environment: Deploy
     needs: Build
     steps:
      - name: Download build artifact
        uses: actions/download-artifact@v6.0.0
        with:
          name: java-app
          
      - name: Azure Login using OIDC
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'demo10011'
          images: '*.war'

      
   

    
