name: Build and deploy java in webapp

on:
 workflow_dispatch: 

permissions:
  id-token: write
  contents: read
  

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v6.0.0

      - name: Set up Java
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '11' # Change if your app uses a different version
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -pl petstore-ee7 -am -Dmaven.compiler.release=11

      
      - name: Upload build artifact
        uses: actions/upload-artifact@v5.0.0
        with:
          name: java-app
          path: petstore-ee7/target/*.war

    
